export enum ErrorMessages {
  VALIDATION = ' DONT BE TOO SMART',
  DOCUMENT_NOT_FOUND = ' DOCUMENT NOT FOUND',
  NO_DOCUMENTS = ' NO AVAILABLE DOCUMENTS',
}

export enum SuccessMessages {
  DOCUMENT_CREATED = ' DOCUMENT CREATED',
  DOCUMENT_UPDATED = ' DOCUMENT UPDATED',
  DOCUMENT_REMOVED = ' DOCUMENT REMOVED',
  DOCUMENT_RETRIEVED = ' SINGLE DOCUMENT RETRIEVED',
  ALL_DOCUMENTS_RETRIEVED = ' ALL DOCUMENTS RETRIEVED',
}
